info:
  app:
    name: catalog-snippet-service
    description: Generates snippets for catalog items

server:
  port: 8016

zipkin:
    collector-hostname: localhost
    
monitoring:
    hostname: localhost
    port: 2003
    period: 1  