info:
  app:
    name: catalog-snippet-service
    description: Generates snippets for catalog items

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 8108

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

snippet:
  iiifImageRootUrl: http://www.nb.no/services/image/resolver/

---
spring:
    profiles: docker

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/